In [31]:
import math
import sympy as sym
import numpy as np
from IPython.display import display, Math

In [2]:
# this is actually hcf
math.gcd(3, 15)

3

In [3]:
a = 16
b = 88

fact = math.gcd(16, 88)

a_mod = int(a / fact)
b_mod = int(b / fact)

display(Math("\\frac{%g}{%g} \\Rightarrow \\frac{%g \\times %g}{%g \\times %g} \\Rightarrow \\frac{%g}{%g}" %(a_mod, b_mod, a_mod, fact, b_mod, fact, a, b)))

<IPython.core.display.Math object>

## Exercises

#### Exercise_1

In [29]:
a,b,c, = sym.symbols("a,b,c")

lhs_gcd = sym.gcd(c*a, c*b)
rhs_gcd = c * sym.gcd(a, b)

lhs_gcd == rhs_gcd

True

#### Exercise_2

In [89]:
m = 10
n = 15
matrix = np.zeros([m, n], dtype=int) + 99

for row_i in range(0, m): 
    for col_i in range(0, n): 
        matrix[row_i, col_i] = math.gcd(row_i + 1, col_i + 1)

print(matrix)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  2  1  2  1  2  1  2  1  2  1  2  1  2  1]
 [ 1  1  3  1  1  3  1  1  3  1  1  3  1  1  3]
 [ 1  2  1  4  1  2  1  4  1  2  1  4  1  2  1]
 [ 1  1  1  1  5  1  1  1  1  5  1  1  1  1  5]
 [ 1  2  3  2  1  6  1  2  3  2  1  6  1  2  3]
 [ 1  1  1  1  1  1  7  1  1  1  1  1  1  7  1]
 [ 1  2  1  4  1  2  1  8  1  2  1  4  1  2  1]
 [ 1  1  3  1  1  3  1  1  9  1  1  3  1  1  3]
 [ 1  2  1  2  5  2  1  2  1 10  1  2  1  2  5]]
